// Generated by gencpp from file deepfind_package/encoders_data.msg
// DO NOT EDIT!


#ifndef DEEPFIND_PACKAGE_MESSAGE_ENCODERS_DATA_H
#define DEEPFIND_PACKAGE_MESSAGE_ENCODERS_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepfind_package
{
template <class ContainerAllocator>
struct encoders_data_
{
  typedef encoders_data_<ContainerAllocator> Type;

  encoders_data_()
    : help()  {
    }
  encoders_data_(const ContainerAllocator& _alloc)
    : help(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _help_type;
  _help_type help;




  typedef boost::shared_ptr< ::deepfind_package::encoders_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepfind_package::encoders_data_<ContainerAllocator> const> ConstPtr;

}; // struct encoders_data_

typedef ::deepfind_package::encoders_data_<std::allocator<void> > encoders_data;

typedef boost::shared_ptr< ::deepfind_package::encoders_data > encoders_dataPtr;
typedef boost::shared_ptr< ::deepfind_package::encoders_data const> encoders_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepfind_package::encoders_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepfind_package::encoders_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepfind_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'deepfind_package': ['/home/giova/DeepFind/catkin_ws/src/deepfind_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepfind_package::encoders_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepfind_package::encoders_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepfind_package::encoders_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepfind_package::encoders_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepfind_package::encoders_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepfind_package::encoders_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepfind_package::encoders_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ded41f8a691465b353a1de637830f92";
  }

  static const char* value(const ::deepfind_package::encoders_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ded41f8a691465bULL;
  static const uint64_t static_value2 = 0x353a1de637830f92ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepfind_package::encoders_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepfind_package/encoders_data";
  }

  static const char* value(const ::deepfind_package::encoders_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepfind_package::encoders_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string help\n\
";
  }

  static const char* value(const ::deepfind_package::encoders_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepfind_package::encoders_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.help);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoders_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepfind_package::encoders_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepfind_package::encoders_data_<ContainerAllocator>& v)
  {
    s << indent << "help: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.help);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPFIND_PACKAGE_MESSAGE_ENCODERS_DATA_H
