(cl:in-package deepfind_package-msg)
(cl:export '(LEFTMOTORPOWER-VAL
          LEFTMOTORPOWER
          RIGHTMOTORPOWER-VAL
          RIGHTMOTORPOWER
          LEFTMOTORDIRECTION-VAL
          LEFTMOTORDIRECTION
          RIGHTMOTORDIRECTION-VAL
          RIGHTMOTORDIRECTION
))